/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUniversityRouteImport } from './routes/app.university'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResumeRouteImport } from './routes/app.resume'
import { Route as AppRecruiterRouteImport } from './routes/app.recruiter'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppInterviewRouteImport } from './routes/app.interview'
import { Route as AppCareerRouteImport } from './routes/app.career'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppUniversityStudentsRouteImport } from './routes/app.university.students'
import { Route as AppUniversitySettingsRouteImport } from './routes/app.university.settings'
import { Route as AppUniversityReportsRouteImport } from './routes/app.university.reports'
import { Route as AppUniversityRecruitersRouteImport } from './routes/app.university.recruiters'
import { Route as AppUniversityDrivesRouteImport } from './routes/app.university.drives'
import { Route as AppUniversityAnalyticsRouteImport } from './routes/app.university.analytics'
import { Route as AppRecruiterSettingsRouteImport } from './routes/app.recruiter.settings'
import { Route as AppRecruiterJobsRouteImport } from './routes/app.recruiter.jobs'
import { Route as AppRecruiterInterviewsRouteImport } from './routes/app.recruiter.interviews'
import { Route as AppRecruiterCompanyRouteImport } from './routes/app.recruiter.company'
import { Route as AppRecruiterCandidatesRouteImport } from './routes/app.recruiter.candidates'
import { Route as AppRecruiterAnalyticsRouteImport } from './routes/app.recruiter.analytics'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminUniversitiesRouteImport } from './routes/app.admin.universities'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminKeysRouteImport } from './routes/app.admin.keys'
import { Route as AppAdminFlagsRouteImport } from './routes/app.admin.flags'
import { Route as AppAdminBillingRouteImport } from './routes/app.admin.billing'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversityRoute = AppUniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterRoute = AppRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversityStudentsRoute = AppUniversityStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppUniversityRoute,
} as any)
const AppUniversitySettingsRoute = AppUniversitySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppUniversityRoute,
} as any)
const AppUniversityReportsRoute = AppUniversityReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppUniversityRoute,
} as any)
const AppUniversityRecruitersRoute = AppUniversityRecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => AppUniversityRoute,
} as any)
const AppUniversityDrivesRoute = AppUniversityDrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => AppUniversityRoute,
} as any)
const AppUniversityAnalyticsRoute = AppUniversityAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppUniversityRoute,
} as any)
const AppRecruiterSettingsRoute = AppRecruiterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterJobsRoute = AppRecruiterJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterInterviewsRoute = AppRecruiterInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterCompanyRoute = AppRecruiterCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterCandidatesRoute = AppRecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterAnalyticsRoute = AppRecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUniversitiesRoute = AppAdminUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminKeysRoute = AppAdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFlagsRoute = AppAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/applications': typeof AppApplicationsRoute
  '/app/career': typeof AppCareerRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recruiter': typeof AppRecruiterRouteWithChildren
  '/app/resume': typeof AppResumeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/university': typeof AppUniversityRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/flags': typeof AppAdminFlagsRoute
  '/app/admin/keys': typeof AppAdminKeysRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/universities': typeof AppAdminUniversitiesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/app/recruiter/candidates': typeof AppRecruiterCandidatesRoute
  '/app/recruiter/company': typeof AppRecruiterCompanyRoute
  '/app/recruiter/interviews': typeof AppRecruiterInterviewsRoute
  '/app/recruiter/jobs': typeof AppRecruiterJobsRoute
  '/app/recruiter/settings': typeof AppRecruiterSettingsRoute
  '/app/university/analytics': typeof AppUniversityAnalyticsRoute
  '/app/university/drives': typeof AppUniversityDrivesRoute
  '/app/university/recruiters': typeof AppUniversityRecruitersRoute
  '/app/university/reports': typeof AppUniversityReportsRoute
  '/app/university/settings': typeof AppUniversitySettingsRoute
  '/app/university/students': typeof AppUniversityStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/applications': typeof AppApplicationsRoute
  '/app/career': typeof AppCareerRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recruiter': typeof AppRecruiterRouteWithChildren
  '/app/resume': typeof AppResumeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/university': typeof AppUniversityRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/flags': typeof AppAdminFlagsRoute
  '/app/admin/keys': typeof AppAdminKeysRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/universities': typeof AppAdminUniversitiesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/app/recruiter/candidates': typeof AppRecruiterCandidatesRoute
  '/app/recruiter/company': typeof AppRecruiterCompanyRoute
  '/app/recruiter/interviews': typeof AppRecruiterInterviewsRoute
  '/app/recruiter/jobs': typeof AppRecruiterJobsRoute
  '/app/recruiter/settings': typeof AppRecruiterSettingsRoute
  '/app/university/analytics': typeof AppUniversityAnalyticsRoute
  '/app/university/drives': typeof AppUniversityDrivesRoute
  '/app/university/recruiters': typeof AppUniversityRecruitersRoute
  '/app/university/reports': typeof AppUniversityReportsRoute
  '/app/university/settings': typeof AppUniversitySettingsRoute
  '/app/university/students': typeof AppUniversityStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/applications': typeof AppApplicationsRoute
  '/app/career': typeof AppCareerRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recruiter': typeof AppRecruiterRouteWithChildren
  '/app/resume': typeof AppResumeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/university': typeof AppUniversityRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/flags': typeof AppAdminFlagsRoute
  '/app/admin/keys': typeof AppAdminKeysRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/universities': typeof AppAdminUniversitiesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/app/recruiter/candidates': typeof AppRecruiterCandidatesRoute
  '/app/recruiter/company': typeof AppRecruiterCompanyRoute
  '/app/recruiter/interviews': typeof AppRecruiterInterviewsRoute
  '/app/recruiter/jobs': typeof AppRecruiterJobsRoute
  '/app/recruiter/settings': typeof AppRecruiterSettingsRoute
  '/app/university/analytics': typeof AppUniversityAnalyticsRoute
  '/app/university/drives': typeof AppUniversityDrivesRoute
  '/app/university/recruiters': typeof AppUniversityRecruitersRoute
  '/app/university/reports': typeof AppUniversityReportsRoute
  '/app/university/settings': typeof AppUniversitySettingsRoute
  '/app/university/students': typeof AppUniversityStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/applications'
    | '/app/career'
    | '/app/interview'
    | '/app/jobs'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recruiter'
    | '/app/resume'
    | '/app/settings'
    | '/app/university'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/billing'
    | '/app/admin/flags'
    | '/app/admin/keys'
    | '/app/admin/settings'
    | '/app/admin/universities'
    | '/app/admin/users'
    | '/app/recruiter/analytics'
    | '/app/recruiter/candidates'
    | '/app/recruiter/company'
    | '/app/recruiter/interviews'
    | '/app/recruiter/jobs'
    | '/app/recruiter/settings'
    | '/app/university/analytics'
    | '/app/university/drives'
    | '/app/university/recruiters'
    | '/app/university/reports'
    | '/app/university/settings'
    | '/app/university/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/admin'
    | '/app/applications'
    | '/app/career'
    | '/app/interview'
    | '/app/jobs'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recruiter'
    | '/app/resume'
    | '/app/settings'
    | '/app/university'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/billing'
    | '/app/admin/flags'
    | '/app/admin/keys'
    | '/app/admin/settings'
    | '/app/admin/universities'
    | '/app/admin/users'
    | '/app/recruiter/analytics'
    | '/app/recruiter/candidates'
    | '/app/recruiter/company'
    | '/app/recruiter/interviews'
    | '/app/recruiter/jobs'
    | '/app/recruiter/settings'
    | '/app/university/analytics'
    | '/app/university/drives'
    | '/app/university/recruiters'
    | '/app/university/reports'
    | '/app/university/settings'
    | '/app/university/students'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/applications'
    | '/app/career'
    | '/app/interview'
    | '/app/jobs'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recruiter'
    | '/app/resume'
    | '/app/settings'
    | '/app/university'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/billing'
    | '/app/admin/flags'
    | '/app/admin/keys'
    | '/app/admin/settings'
    | '/app/admin/universities'
    | '/app/admin/users'
    | '/app/recruiter/analytics'
    | '/app/recruiter/candidates'
    | '/app/recruiter/company'
    | '/app/recruiter/interviews'
    | '/app/recruiter/jobs'
    | '/app/recruiter/settings'
    | '/app/university/analytics'
    | '/app/university/drives'
    | '/app/university/recruiters'
    | '/app/university/reports'
    | '/app/university/settings'
    | '/app/university/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/university': {
      id: '/app/university'
      path: '/university'
      fullPath: '/app/university'
      preLoaderRoute: typeof AppUniversityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recruiter': {
      id: '/app/recruiter'
      path: '/recruiter'
      fullPath: '/app/recruiter'
      preLoaderRoute: typeof AppRecruiterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interview': {
      id: '/app/interview'
      path: '/interview'
      fullPath: '/app/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/university/students': {
      id: '/app/university/students'
      path: '/students'
      fullPath: '/app/university/students'
      preLoaderRoute: typeof AppUniversityStudentsRouteImport
      parentRoute: typeof AppUniversityRoute
    }
    '/app/university/settings': {
      id: '/app/university/settings'
      path: '/settings'
      fullPath: '/app/university/settings'
      preLoaderRoute: typeof AppUniversitySettingsRouteImport
      parentRoute: typeof AppUniversityRoute
    }
    '/app/university/reports': {
      id: '/app/university/reports'
      path: '/reports'
      fullPath: '/app/university/reports'
      preLoaderRoute: typeof AppUniversityReportsRouteImport
      parentRoute: typeof AppUniversityRoute
    }
    '/app/university/recruiters': {
      id: '/app/university/recruiters'
      path: '/recruiters'
      fullPath: '/app/university/recruiters'
      preLoaderRoute: typeof AppUniversityRecruitersRouteImport
      parentRoute: typeof AppUniversityRoute
    }
    '/app/university/drives': {
      id: '/app/university/drives'
      path: '/drives'
      fullPath: '/app/university/drives'
      preLoaderRoute: typeof AppUniversityDrivesRouteImport
      parentRoute: typeof AppUniversityRoute
    }
    '/app/university/analytics': {
      id: '/app/university/analytics'
      path: '/analytics'
      fullPath: '/app/university/analytics'
      preLoaderRoute: typeof AppUniversityAnalyticsRouteImport
      parentRoute: typeof AppUniversityRoute
    }
    '/app/recruiter/settings': {
      id: '/app/recruiter/settings'
      path: '/settings'
      fullPath: '/app/recruiter/settings'
      preLoaderRoute: typeof AppRecruiterSettingsRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/jobs': {
      id: '/app/recruiter/jobs'
      path: '/jobs'
      fullPath: '/app/recruiter/jobs'
      preLoaderRoute: typeof AppRecruiterJobsRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/interviews': {
      id: '/app/recruiter/interviews'
      path: '/interviews'
      fullPath: '/app/recruiter/interviews'
      preLoaderRoute: typeof AppRecruiterInterviewsRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/company': {
      id: '/app/recruiter/company'
      path: '/company'
      fullPath: '/app/recruiter/company'
      preLoaderRoute: typeof AppRecruiterCompanyRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/candidates': {
      id: '/app/recruiter/candidates'
      path: '/candidates'
      fullPath: '/app/recruiter/candidates'
      preLoaderRoute: typeof AppRecruiterCandidatesRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/analytics': {
      id: '/app/recruiter/analytics'
      path: '/analytics'
      fullPath: '/app/recruiter/analytics'
      preLoaderRoute: typeof AppRecruiterAnalyticsRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/universities': {
      id: '/app/admin/universities'
      path: '/universities'
      fullPath: '/app/admin/universities'
      preLoaderRoute: typeof AppAdminUniversitiesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/keys': {
      id: '/app/admin/keys'
      path: '/keys'
      fullPath: '/app/admin/keys'
      preLoaderRoute: typeof AppAdminKeysRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/flags': {
      id: '/app/admin/flags'
      path: '/flags'
      fullPath: '/app/admin/flags'
      preLoaderRoute: typeof AppAdminFlagsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/billing': {
      id: '/app/admin/billing'
      path: '/billing'
      fullPath: '/app/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminFlagsRoute: typeof AppAdminFlagsRoute
  AppAdminKeysRoute: typeof AppAdminKeysRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUniversitiesRoute: typeof AppAdminUniversitiesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminFlagsRoute: AppAdminFlagsRoute,
  AppAdminKeysRoute: AppAdminKeysRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUniversitiesRoute: AppAdminUniversitiesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRecruiterRouteChildren {
  AppRecruiterAnalyticsRoute: typeof AppRecruiterAnalyticsRoute
  AppRecruiterCandidatesRoute: typeof AppRecruiterCandidatesRoute
  AppRecruiterCompanyRoute: typeof AppRecruiterCompanyRoute
  AppRecruiterInterviewsRoute: typeof AppRecruiterInterviewsRoute
  AppRecruiterJobsRoute: typeof AppRecruiterJobsRoute
  AppRecruiterSettingsRoute: typeof AppRecruiterSettingsRoute
}

const AppRecruiterRouteChildren: AppRecruiterRouteChildren = {
  AppRecruiterAnalyticsRoute: AppRecruiterAnalyticsRoute,
  AppRecruiterCandidatesRoute: AppRecruiterCandidatesRoute,
  AppRecruiterCompanyRoute: AppRecruiterCompanyRoute,
  AppRecruiterInterviewsRoute: AppRecruiterInterviewsRoute,
  AppRecruiterJobsRoute: AppRecruiterJobsRoute,
  AppRecruiterSettingsRoute: AppRecruiterSettingsRoute,
}

const AppRecruiterRouteWithChildren = AppRecruiterRoute._addFileChildren(
  AppRecruiterRouteChildren,
)

interface AppUniversityRouteChildren {
  AppUniversityAnalyticsRoute: typeof AppUniversityAnalyticsRoute
  AppUniversityDrivesRoute: typeof AppUniversityDrivesRoute
  AppUniversityRecruitersRoute: typeof AppUniversityRecruitersRoute
  AppUniversityReportsRoute: typeof AppUniversityReportsRoute
  AppUniversitySettingsRoute: typeof AppUniversitySettingsRoute
  AppUniversityStudentsRoute: typeof AppUniversityStudentsRoute
}

const AppUniversityRouteChildren: AppUniversityRouteChildren = {
  AppUniversityAnalyticsRoute: AppUniversityAnalyticsRoute,
  AppUniversityDrivesRoute: AppUniversityDrivesRoute,
  AppUniversityRecruitersRoute: AppUniversityRecruitersRoute,
  AppUniversityReportsRoute: AppUniversityReportsRoute,
  AppUniversitySettingsRoute: AppUniversitySettingsRoute,
  AppUniversityStudentsRoute: AppUniversityStudentsRoute,
}

const AppUniversityRouteWithChildren = AppUniversityRoute._addFileChildren(
  AppUniversityRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCareerRoute: typeof AppCareerRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppJobsRoute: typeof AppJobsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecruiterRoute: typeof AppRecruiterRouteWithChildren
  AppResumeRoute: typeof AppResumeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUniversityRoute: typeof AppUniversityRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppApplicationsRoute: AppApplicationsRoute,
  AppCareerRoute: AppCareerRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppJobsRoute: AppJobsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecruiterRoute: AppRecruiterRouteWithChildren,
  AppResumeRoute: AppResumeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUniversityRoute: AppUniversityRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
